//
// Generated file, do not edit! Created by nedtool 5.4 from sdn_message.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __SDN_MESSAGE_M_H
#define __SDN_MESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>sdn_message.msg:17</tt> by nedtool.
 * <pre>
 * message sdn_message
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class sdn_message : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int hopCount;

  private:
    void copy(const sdn_message& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const sdn_message&);

  public:
    sdn_message(const char *name=nullptr, short kind=0);
    sdn_message(const sdn_message& other);
    virtual ~sdn_message();
    sdn_message& operator=(const sdn_message& other);
    virtual sdn_message *dup() const override {return new sdn_message(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const sdn_message& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, sdn_message& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SDN_MESSAGE_M_H

